name: Update Credly Badges

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:       # Allows manual trigger anytime

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update Credly Badges
        uses: nicklegan/github-credly-badge-action@v2.0.0
        with:
          credly_username: manjusree-pushphaa
          token: ${{ secrets.GITHUB_TOKEN }}
